apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kompass-admission-controller.cr" . }}
  labels:
    app: {{ include "kompass-admission-controller.fullname" . }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledobject
    verbs:
      - get
      - list
  - apiGroups:
      - karpenter.sh
    resources:
      - nodepools
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - kompass.zesty.co
    resources:
      - workloaddescriptors
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zesty.co
    resources:
      - managedworkloads
      - managednodepools
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
