apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kompass-admission-controller.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kompass-admission-controller.fullname" . }}-cert
webhooks:
- name: nodepool.karpenter.sh
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
  rules:
    - operations:
        - "CREATE"
        - "UPDATE"
        - "CONNECT"
      apiGroups:
        - "apps"
      apiVersions:
        - "v1"
      resources:
        - "deployments"
    - operations:
        - "CREATE"
        - "UPDATE"
        - "CONNECT"
      apiGroups:
        - "autoscaling"
      apiVersions:
        - "v1"
        - "v2beta1"
        - "v2beta2"
        - "v2"
      resources:
        - "horizontalpodautoscalers"
    - operations:
        - "CREATE"
        - "UPDATE"
        - "CONNECT"
      apiGroups:
        - "karpenter.sh"
      apiVersions:
        - "v1beta1"
        - "v1"
      resources:
        - "nodepools"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore" | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kompass-admission-controller.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}  # Ensure it's deployed in the correct namespace
  annotations:
  {{ if and .Values.global .Values.global.useHelmPriorityHooks }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "20"
  {{ end }}
    cert-manager.io/disable-name-generation: "true"
  labels:
    {{- include "kompass-admission-controller.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kompass-admission-controller.fullname" . }}-cert
  dnsNames:
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: {{ if and .Values.global .Values.global.clusterIssuerName }}