{{- $cert := include "kompass-admission-controller.cert" . | fromYaml -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kompass-admission-controller.fullname" . }}-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "5"
webhooks:
- name: nodepool.karpenter.sh
  clientConfig:
    service:
      name: {{ include "kompass-admission-controller.serviceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
    caBundle: {{ include "kompass-admission-controller.cert" . | fromYaml | dig "Cert" "" | b64enc }}
  rules:
  - operations: ["CREATE", "UPDATE", "CONNECT"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  - operations: ["CREATE", "UPDATE", "CONNECT"]
    apiGroups: ["karpenter.sh"]
    apiVersions: ["v1beta1", "v1"]
    resources: ["nodepools"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Ignore
