apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "kompass-admission-controller.pdb" . }}
  labels:
    app: {{ include "kompass-admission-controller.fullname" . }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ include "kompass-admission-controller.fullname" . }}
