apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.zesty-admission-controller-tls-ca
  labels:
    app: {{ include "kompass-admission-controller.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/tls
data:
  tls.key: {{ include "kompass-admission-controller.cert" . | fromYaml | dig "Key" "" | b64enc }}
  tls.crt: {{ include "kompass-admission-controller.cert" . | fromYaml | dig "Cert" "" | b64enc }}
