apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-admission-controller.sa" . }}
  labels:
    app: {{ include "kompass-admission-controller.fullname" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}
