apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ include "kompass-admission-controller.fullname" . }}
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: grpc
    port: {{ .Values.grpc.port }}
    targetPort: {{ .Values.grpc.port }}
  type: ClusterIP
